import type { Change, EvidenceRecord } from "../types/domain";

/**
 * Mock records standing in for the backend.
 *
 * These are deliberately realistic rather than uniform: some stories
 * have gaps in their business impact, some were rejected, one was
 * resolved with no JDE change at all. The dashboard computes every
 * metric from this list, so editing a record here changes the numbers
 * on the Home page — which is exactly how it will behave against the
 * real API.
 */

const ev = (
  n: number,
  stage: string,
  detail: string,
  actor: string,
  at: string
): EvidenceRecord => ({
  entryId: `E${n}`,
  stage,
  detail,
  actor,
  capturedAt: at,
  prevHash: n === 1 ? "GENESIS" : `hash-${n - 1}`,
  entryHash: `hash-${n}`,
});

export const MOCK_CHANGES: Change[] = [
  {
    id: "CHG-1042",
    customerId: "vdb",
    title: "Update SO default document type",
    source: "Support / Topdesk",
    sourceReference: "Topdesk #4521",
    originalRequest:
      "Our order entry people keep having to change the document type by hand on every sales order. It should just default to SO. It's been like this since the last update.",
    changeType: "Configuration",
    state: "BACKLOG_READY",
    priority: "High",
    complexitySignal: "Low",
    businessImpact: {
      financialImpact: "Around 2 hours per week of manual correction across the team (stated in ticket)",
      operationalReach: "All sales order entry clerks, daily",
      riskCompliance: "",
      strategicAlignment: "",
      urgency: "Not time-bound, but affects daily work",
    },
    createdAt: "2026-09-17T09:12:00Z",
    updatedAt: "2026-09-19T10:12:00Z",
    updatedBy: "AI Architect",
    userStory: {
      statement:
        "As a sales order administrator, I want the document type on version CIQ0001 to default to SO, so that clerks stop correcting it manually on every order.",
      businessContext:
        "Order entry clerks in the Arnhem office correct the document type on roughly every sales order they raise. The default changed during the last configuration update and was not restored.",
      acceptanceCriteria: [
        { id: "AC1", text: "A new sales order raised on version CIQ0001 shows document type SO without the clerk changing it.", verifiedBy: "T1" },
        { id: "AC2", text: "Existing orders already raised are unaffected.", verifiedBy: "T2" },
      ],
      testScript: [
        { id: "T1", action: "Raise a new sales order on P4210 version CIQ0001", expected: "Document type field is pre-filled with SO" },
        { id: "T2", action: "Open a sales order created before the change", expected: "Its document type is unchanged" },
      ],
      openQuestions: [],
      qualityStatus: "passed",
      revisionCount: 1,
    },
    evidence: [
      ev(1, "Intake", "Story captured from Topdesk #4521", "AI Intake", "2026-09-17T09:12:00Z"),
      ev(2, "Quality gate", "Failed on vague acceptance criteria, returned to Improve", "AI Check", "2026-09-17T09:20:00Z"),
      ev(3, "Quality gate", "Passed all eight criteria, proposed to backlog", "AI Check", "2026-09-17T09:31:00Z"),
    ],
  },
  {
    id: "CHG-1041",
    customerId: "vdb",
    title: "Add customer validation on order entry",
    source: "Business",
    sourceReference: "Workshop note, 12 Sept",
    originalRequest:
      "We want a check so that orders can't be entered for customers who are on credit hold.",
    changeType: "Functional Change",
    state: "EXECUTING",
    priority: "High",
    complexitySignal: "Medium",
    businessImpact: {
      financialImpact: "Prevents orders against bad debt; finance estimated €40k exposure last quarter",
      operationalReach: "All order entry, every order",
      riskCompliance: "Reduces credit exposure",
      strategicAlignment: "Supports the credit control tightening initiative",
      urgency: "Wanted before quarter end",
    },
    createdAt: "2026-09-15T11:00:00Z",
    updatedAt: "2026-09-19T09:48:00Z",
    updatedBy: "AI Builder",
    userStory: {
      statement:
        "As a credit controller, I want order entry blocked for customers on credit hold, so that we stop shipping against bad debt.",
      businessContext: "Credit control currently finds these orders after the fact and cancels them manually.",
      acceptanceCriteria: [
        { id: "AC1", text: "An order for a customer on credit hold is refused at entry with a clear message.", verifiedBy: "T1" },
      ],
      testScript: [
        { id: "T1", action: "Enter an order for a customer flagged on credit hold", expected: "Entry is refused with the credit hold message" },
      ],
      openQuestions: [],
      qualityStatus: "passed",
      revisionCount: 0,
    },
    storyApproval: {
      approvalId: "AP-1041-S",
      kind: "story",
      status: "approved",
      approvedBy: "Hendro",
      approvedAt: "2026-09-16T08:30:00Z",
      note: "Clear business case, quarter-end deadline is real",
    },
    architectDecision: {
      recommendedRoute: "Functional Agent",
      confidence: 0.86,
      existingFunctionalityFound:
        "Credit hold checking exists in standard JDE but is switched off on this version's processing options.",
      alternativesConsidered: [
        { approach: "Standard functionality as-is", whyNot: "The check exists but is disabled on this version — it needs a configuration change to switch on." },
        { approach: "Technical Agent (new validation)", whyNot: "Unnecessary: no new development is needed when a supported processing option already does this." },
      ],
      objectsAffected: ["P4210 / CIQ0001 / Credit Check processing option"],
      dependenciesAndConflicts: ["Applies to all orders on this version, including EDI-created orders"],
      rollbackStrategy: "Restore the prior processing option value (captured before the write).",
      decidedAt: "2026-09-17T14:02:00Z",
    },
    implementationSpec: {
      sequence: [
        "Read and record the current credit check processing option value",
        "Set the credit check processing option to active",
        "Run the credit hold acceptance orchestration",
      ],
      requiredMcpOperations: ["get_processing_options", "set_processing_option", "run_orchestration"],
      humanActionsRequired: ["Approve the exact change", "Validate the result before CNC hand-off"],
      validationApproach: "ORCH_VERIFY_CREDIT_HOLD, comparing refusal behaviour before and after",
    },
    exactChange: {
      tool: "set_processing_option",
      application: "P4210",
      version: "CIQ0001",
      option: "CREDITCHK",
      currentValue: "0 (off)",
      proposedValue: "1 (on)",
      environment: "DEV",
      testOrchestration: "ORCH_VERIFY_CREDIT_HOLD",
    },
    changeApproval: {
      approvalId: "AP-1041-C",
      kind: "change",
      status: "approved",
      changeHash: "9f2c1a...e77b",
      approvedBy: "Hendro",
      approvedAt: "2026-09-19T09:40:00Z",
      expiresAt: "2026-09-20T09:40:00Z",
      note: "Correct option and version",
    },
    testSpecification: {
      mode: "JDE automated",
      orchestrationName: "ORCH_VERIFY_CREDIT_HOLD",
      steps: [{ id: "T1", action: "Enter an order for a held customer", expected: "Refused with credit hold message" }],
    },
    testResult: { outcome: "not run" },
    evidence: [
      ev(1, "Intake", "Captured from workshop note", "AI Intake", "2026-09-15T11:00:00Z"),
      ev(2, "Quality gate", "Passed, proposed to backlog", "AI Check", "2026-09-15T11:40:00Z"),
      ev(3, "Backlog approval", "Approved by Hendro", "Hendro", "2026-09-16T08:30:00Z"),
      ev(4, "Architect decision", "Routed to Functional Agent, confidence 0.86", "AI Architect", "2026-09-17T14:02:00Z"),
      ev(5, "Change approval", "Exact change approved by Hendro", "Hendro", "2026-09-19T09:40:00Z"),
    ],
  },
  {
    id: "CHG-1040",
    customerId: "vdb",
    title: "Investigate pricing discrepancy on contract orders",
    source: "Support / Topdesk",
    sourceReference: "Topdesk #4498",
    originalRequest: "Prices on contract orders look wrong sometimes. Can someone check?",
    changeType: "Investigation",
    state: "REFINING",
    priority: "Medium",
    complexitySignal: "Unknown",
    businessImpact: {
      financialImpact: "",
      operationalReach: "",
      riskCompliance: "",
      strategicAlignment: "",
      urgency: "",
    },
    createdAt: "2026-09-19T09:21:00Z",
    updatedAt: "2026-09-19T09:21:00Z",
    updatedBy: "AI Intake",
    userStory: {
      statement: "As a sales administrator, I want contract order pricing to be correct, so that customers are invoiced the agreed amount.",
      businessContext: "Reported as intermittent. No specific order numbers or amounts were given in the ticket.",
      acceptanceCriteria: [],
      testScript: [],
      openQuestions: [
        "Which specific orders showed the wrong price? Without at least one example this cannot be reproduced.",
        "Was the price wrong on the order, the invoice, or both?",
        "Is this limited to one customer, one contract, or widespread?",
      ],
      qualityStatus: "needs_revision",
      revisionCount: 1,
    },
    evidence: [
      ev(1, "Intake", "Captured from Topdesk #4498", "AI Intake", "2026-09-19T09:21:00Z"),
      ev(2, "Quality gate", "Failed: no measurable definition of done, business impact not stated, no reproducible example", "AI Check", "2026-09-19T09:26:00Z"),
    ],
  },
  {
    id: "CHG-1039",
    customerId: "vdb",
    title: "Change processing option for backorder release",
    source: "Optimisation",
    sourceReference: "Improvement register 2026-31",
    originalRequest: "Backorder release should not require a second confirmation step for warehouse staff.",
    changeType: "Configuration",
    state: "TESTING",
    priority: "Medium",
    complexitySignal: "Low",
    businessImpact: {
      financialImpact: "Saves roughly 20 seconds per release, several hundred releases per week",
      operationalReach: "Warehouse team, daily",
      riskCompliance: "None identified",
      strategicAlignment: "",
      urgency: "Not time-bound",
    },
    createdAt: "2026-09-14T08:00:00Z",
    updatedAt: "2026-09-19T08:55:00Z",
    updatedBy: "AI Tester",
    userStory: {
      statement: "As a warehouse operator, I want backorder release to complete in one step, so that I stop confirming the same action twice.",
      businessContext: "The second confirmation was added for a process that no longer exists.",
      acceptanceCriteria: [{ id: "AC1", text: "Releasing a backorder completes without a second confirmation prompt.", verifiedBy: "T1" }],
      testScript: [{ id: "T1", action: "Release a backorder", expected: "Completes in one step, no second prompt" }],
      openQuestions: [],
      qualityStatus: "passed",
      revisionCount: 0,
    },
    storyApproval: { approvalId: "AP-1039-S", kind: "story", status: "approved", approvedBy: "Hendro", approvedAt: "2026-09-15T09:00:00Z", note: "" },
    architectDecision: {
      recommendedRoute: "Functional Agent",
      confidence: 0.91,
      existingFunctionalityFound: "The confirmation is controlled by a processing option on the release version.",
      alternativesConsidered: [{ approach: "Standard functionality as-is", whyNot: "The prompt is configured on, so it needs a configuration change." }],
      objectsAffected: ["P4210 / CIQ0004 / CONFIRMSTEP"],
      dependenciesAndConflicts: [],
      rollbackStrategy: "Restore the prior processing option value.",
      decidedAt: "2026-09-16T10:00:00Z",
    },
    exactChange: {
      tool: "set_processing_option",
      application: "P4210",
      version: "CIQ0004",
      option: "CONFIRMSTEP",
      currentValue: "1",
      proposedValue: "0",
      environment: "DEV",
      testOrchestration: "ORCH_VERIFY_BACKORDER",
    },
    changeApproval: { approvalId: "AP-1039-C", kind: "change", status: "approved", changeHash: "4b81de...2c90", approvedBy: "Hendro", approvedAt: "2026-09-18T15:00:00Z", note: "" },
    testSpecification: { mode: "JDE automated", orchestrationName: "ORCH_VERIFY_BACKORDER", steps: [{ id: "T1", action: "Release a backorder", expected: "One step, no second prompt" }] },
    testResult: { outcome: "pass", ranAt: "2026-09-19T08:55:00Z", detail: "Release completed in a single step; no regression on partial releases." },
    evidence: [
      ev(1, "Intake", "Captured from improvement register", "AI Intake", "2026-09-14T08:00:00Z"),
      ev(2, "Backlog approval", "Approved by Hendro", "Hendro", "2026-09-15T09:00:00Z"),
      ev(3, "Change approval", "Exact change approved", "Hendro", "2026-09-18T15:00:00Z"),
      ev(4, "Execution", "Processing option CONFIRMSTEP set 1 -> 0 in DEV", "AI Functional Agent", "2026-09-19T08:40:00Z"),
      ev(5, "Test", "ORCH_VERIFY_BACKORDER passed", "AI Tester", "2026-09-19T08:55:00Z"),
    ],
  },
  {
    id: "CHG-1038",
    customerId: "vdb",
    title: "Add UDC value for new shipping condition",
    source: "Business",
    sourceReference: "Email, logistics manager",
    originalRequest: "We need a new shipping condition code for the temperature-controlled route.",
    changeType: "Configuration",
    state: "CLOSED",
    priority: "Low",
    complexitySignal: "Low",
    businessImpact: {
      financialImpact: "",
      operationalReach: "Logistics planners, occasional use",
      riskCompliance: "",
      strategicAlignment: "Supports the cold chain expansion",
      urgency: "Needed before the new route goes live on 1 October",
    },
    createdAt: "2026-09-10T10:00:00Z",
    updatedAt: "2026-09-18T08:32:00Z",
    updatedBy: "AI Tester",
    userStory: {
      statement: "As a logistics planner, I want a shipping condition code for temperature-controlled transport, so that I can plan the cold chain route correctly.",
      businessContext: "The new route starts 1 October and has no code today.",
      acceptanceCriteria: [{ id: "AC1", text: "The new shipping condition is selectable on an order.", verifiedBy: "T1" }],
      testScript: [{ id: "T1", action: "Select the new shipping condition on an order", expected: "Code is available and saves correctly" }],
      openQuestions: [],
      qualityStatus: "passed",
      revisionCount: 0,
    },
    storyApproval: { approvalId: "AP-1038-S", kind: "story", status: "approved", approvedBy: "Hendro", approvedAt: "2026-09-11T09:00:00Z", note: "" },
    testResult: { outcome: "pass", ranAt: "2026-09-17T14:00:00Z" },
    humanValidation: { validatedBy: "M. de Vries", validatedAt: "2026-09-17T16:00:00Z", note: "Confirmed with the logistics team, code appears as expected." },
    evidence: [
      ev(1, "Intake", "Captured from email", "AI Intake", "2026-09-10T10:00:00Z"),
      ev(2, "Backlog approval", "Approved by Hendro", "Hendro", "2026-09-11T09:00:00Z"),
      ev(3, "Execution", "UDC value added in DEV", "AI Functional Agent", "2026-09-17T13:00:00Z"),
      ev(4, "Test", "Passed", "AI Tester", "2026-09-17T14:00:00Z"),
      ev(5, "Validation", "Confirmed by M. de Vries", "M. de Vries", "2026-09-17T16:00:00Z"),
      ev(6, "Closure", "Written back to requester, confirmed solved", "AI Intake", "2026-09-18T08:32:00Z"),
    ],
    closure: {
      whatChanged: "A new shipping condition code was added for temperature-controlled transport.",
      businessFacingResult: "You can now select the temperature-controlled route when entering an order.",
      limitations: "The code is available in DEV; CNC will promote it before 1 October.",
      sourceUpdateStatus: "written back",
      requesterConfirmation: "solved",
      closedAt: "2026-09-18T08:32:00Z",
    },
  },
  {
    id: "CHG-1036",
    customerId: "nhd",
    title: "Add sales region validation",
    source: "Business",
    sourceReference: "Sales ops request",
    originalRequest: "Orders should not be saved without a sales region.",
    changeType: "Functional Change",
    state: "BACKLOG_READY",
    priority: "Medium",
    complexitySignal: "Medium",
    businessImpact: {
      financialImpact: "",
      operationalReach: "All order entry",
      riskCompliance: "Improves reporting accuracy for regional analysis",
      strategicAlignment: "",
      urgency: "",
    },
    createdAt: "2026-09-16T13:00:00Z",
    updatedAt: "2026-09-18T11:00:00Z",
    updatedBy: "AI Check",
    userStory: {
      statement: "As a sales operations analyst, I want sales region to be mandatory on order entry, so that regional reporting is complete.",
      businessContext: "Around 8% of orders last quarter had no region set, which breaks the regional split.",
      acceptanceCriteria: [{ id: "AC1", text: "An order cannot be saved without a sales region.", verifiedBy: "T1" }],
      testScript: [{ id: "T1", action: "Save an order with no sales region", expected: "Save is refused with a clear message" }],
      openQuestions: [],
      qualityStatus: "passed",
      revisionCount: 0,
    },
    evidence: [ev(1, "Intake", "Captured from sales ops request", "AI Intake", "2026-09-16T13:00:00Z")],
  },
  {
    id: "CHG-1034",
    customerId: "nhd",
    title: "Change purchase order tolerance for P4310",
    source: "DevOps",
    sourceReference: "DevOps #882",
    originalRequest: "Raise the PO receipt tolerance from 2% to 5%.",
    changeType: "Configuration",
    state: "BACKLOG_READY",
    priority: "Medium",
    complexitySignal: "Low",
    businessImpact: {
      financialImpact: "",
      operationalReach: "Goods receipt team",
      riskCompliance: "Widening tolerance reduces control — finance sign-off expected",
      strategicAlignment: "",
      urgency: "",
    },
    createdAt: "2026-09-16T09:00:00Z",
    updatedAt: "2026-09-17T10:00:00Z",
    updatedBy: "AI Check",
    evidence: [ev(1, "Intake", "Captured from DevOps #882", "AI Intake", "2026-09-16T09:00:00Z")],
  },
  {
    id: "CHG-1033",
    customerId: "nhd",
    title: "New report for open backorders by region",
    source: "Business",
    sourceReference: "Management request",
    originalRequest: "Can we get a report of open backorders split by region, weekly?",
    changeType: "Technical Change",
    state: "BACKLOG_READY",
    priority: "Low",
    complexitySignal: "High",
    businessImpact: {
      financialImpact: "",
      operationalReach: "Management, weekly",
      riskCompliance: "",
      strategicAlignment: "",
      urgency: "",
    },
    createdAt: "2026-09-15T15:00:00Z",
    updatedAt: "2026-09-16T12:00:00Z",
    updatedBy: "AI Check",
    evidence: [ev(1, "Intake", "Captured from management request", "AI Intake", "2026-09-15T15:00:00Z")],
  },
  {
    id: "CHG-1031",
    customerId: "mrv",
    title: "Order entry screen is slow in the afternoon",
    source: "Support / Topdesk",
    sourceReference: "Topdesk #4410",
    originalRequest: "The order screen gets really slow after lunch most days.",
    changeType: "Investigation",
    state: "RESOLVED_WITHOUT_CHANGE",
    priority: "Medium",
    complexitySignal: "Unknown",
    businessImpact: {
      financialImpact: "",
      operationalReach: "Order entry team, afternoons",
      riskCompliance: "",
      strategicAlignment: "",
      urgency: "",
    },
    createdAt: "2026-09-08T14:00:00Z",
    updatedAt: "2026-09-12T11:00:00Z",
    updatedBy: "AI Architect",
    userStory: {
      statement: "As an order entry clerk, I want the order screen to stay responsive in the afternoon, so that I can work at a steady pace.",
      businessContext: "Reported as a daily slowdown after roughly 13:00.",
      acceptanceCriteria: [{ id: "AC1", text: "Order screen response stays under 2 seconds during afternoon peak." }],
      testScript: [],
      openQuestions: [],
      qualityStatus: "passed",
      revisionCount: 0,
    },
    storyApproval: { approvalId: "AP-1031-S", kind: "story", status: "approved", approvedBy: "Hendro", approvedAt: "2026-09-09T09:00:00Z", note: "" },
    architectDecision: {
      recommendedRoute: "Resolve without Change",
      confidence: 0.79,
      existingFunctionalityFound:
        "The slowdown coincides exactly with the scheduled afternoon UBE batch, which is an infrastructure scheduling matter rather than a JDE configuration or development issue.",
      alternativesConsidered: [
        { approach: "Configuration change", whyNot: "Nothing in the application configuration affects batch scheduling." },
        { approach: "Technical Agent", whyNot: "No development would address a scheduling overlap." },
      ],
      objectsAffected: [],
      dependenciesAndConflicts: [],
      rollbackStrategy: "Not applicable — no change was made.",
      decidedAt: "2026-09-12T11:00:00Z",
    },
    evidence: [
      ev(1, "Intake", "Captured from Topdesk #4410", "AI Intake", "2026-09-08T14:00:00Z"),
      ev(2, "Backlog approval", "Approved for analysis", "Hendro", "2026-09-09T09:00:00Z"),
      ev(3, "Architect decision", "Resolved without change: overlaps the scheduled afternoon UBE batch", "AI Architect", "2026-09-12T11:00:00Z"),
    ],
    closure: {
      whatChanged: "No JD Edwards change was made.",
      businessFacingResult:
        "The afternoon slowdown lines up with a scheduled batch job, not an order entry problem. This has been passed to infrastructure to reschedule.",
      limitations: "If the slowdown continues after the batch is moved, raise a new request with timings.",
      sourceUpdateStatus: "written back",
      requesterConfirmation: "solved",
      closedAt: "2026-09-12T11:30:00Z",
    },
  },
  {
    id: "CHG-1029",
    customerId: "mrv",
    title: "Allow negative inventory adjustments without approval",
    source: "Business",
    sourceReference: "Warehouse request",
    originalRequest: "Warehouse wants to post negative adjustments without waiting for a supervisor.",
    changeType: "Configuration",
    state: "REJECTED",
    priority: "Low",
    complexitySignal: "Low",
    businessImpact: {
      financialImpact: "",
      operationalReach: "Warehouse team",
      riskCompliance: "Removing the approval step weakens inventory control",
      strategicAlignment: "",
      urgency: "",
    },
    createdAt: "2026-09-05T10:00:00Z",
    updatedAt: "2026-09-06T09:00:00Z",
    updatedBy: "Hendro",
    userStory: {
      statement: "As a warehouse operator, I want to post negative inventory adjustments without supervisor approval, so that stock corrections are faster.",
      businessContext: "Operators report waiting for a supervisor slows down stock corrections.",
      acceptanceCriteria: [{ id: "AC1", text: "A negative adjustment posts without a supervisor approval step." }],
      testScript: [],
      openQuestions: [],
      qualityStatus: "passed",
      revisionCount: 0,
    },
    storyApproval: {
      approvalId: "AP-1029-S",
      kind: "story",
      status: "rejected",
      approvedBy: "Hendro",
      approvedAt: "2026-09-06T09:00:00Z",
      note: "Removing the approval step on negative adjustments weakens a control finance relies on. Not proceeding without finance sign-off on the risk.",
    },
    evidence: [
      ev(1, "Intake", "Captured from warehouse request", "AI Intake", "2026-09-05T10:00:00Z"),
      ev(2, "Backlog decision", "Rejected: weakens an inventory control without finance sign-off", "Hendro", "2026-09-06T09:00:00Z"),
    ],
  },
];
